/*
 * Copyright (c) 2026 IsArvin.
 * This file is part of ctyun-cli. Please refer to the LICENCE file for licence information.
 */

package openapipipeline

// catalogRepairPhraseLabels gives stable localized labels to reusable response
// concepts discovered by repository-wide catalog review.
var catalogRepairPhraseLabels = map[string]string{
	"actual_value":                   "实际值",
	"alarm_name":                     "告警名称",
	"alarm_time":                     "告警时间",
	"auto_renew_cycle_count":         "自动续订周期数",
	"auto_renew_cycle_type":          "自动续订周期类型",
	"auto_renew_status":              "自动续订状态",
	"az_strategy":                    "可用区策略",
	"backup_restore_done_time":       "备份恢复完成时间",
	"backup_snap_is_new":             "是否为最新快照",
	"backup_tgt_instance_name":       "备份恢复目标云主机名称",
	"bandwidth_base":                 "基准带宽",
	"bandwidth_max":                  "最大带宽",
	"base_bandwidth":                 "基准带宽",
	"build_status":                   "构建状态",
	"cert_config":                    "HTTPS 证书信息",
	"cname_valid":                    "CNAME 是否有效",
	"code":                           "错误码",
	"cluster_type":                   "集群类型",
	"cluster_type_name":              "集群类型名称",
	"comparison_operator":            "比较符",
	"compute_node_quantity":          "计算节点数量",
	"config_id":                      "伸缩配置 ID",
	"config_name":                    "伸缩配置名称",
	"cooldown":                       "冷却时间",
	"cpu_quantity":                   "计算节点 CPU 总核数",
	"cpu_frequency":                  "CPU 频率",
	"cpu_manufacturer":               "CPU 厂商",
	"create_time":                    "创建时间",
	"create_type":                    "创建类型",
	"ctrn":                           "层唯一标识",
	"cycle":                          "循环方式",
	"dedicated_host_description":     "专属宿主机描述",
	"dedicated_host_idlist":          "专属宿主机 ID 列表",
	"dedicated_host_name":            "专属宿主机名称",
	"dedicated_host_resource_id":     "专属宿主机资源 ID",
	"data_volume_interface":          "数据盘接口",
	"data_volume_type":               "数据盘类型",
	"delegate_name":                  "委托名称",
	"delete_protection":              "删除保护",
	"disk_mode":                      "云硬盘模式",
	"end_time":                       "结束时间",
	"enable_shadow_vpc":              "存储高速网络支持",
	"error":                          "错误码",
	"error_code":                     "错误码",
	"event_type":                     "事件类型",
	"execution_mode":                 "执行方式",
	"execution_result":               "执行结果",
	"execution_workflow_dsl":         "工作流执行定义",
	"expected_count":                 "期望数量",
	"fixed_iplist":                   "固定 IP 列表",
	"format":                         "镜像格式",
	"flag":                           "云硬盘用途",
	"flavor_cpuscope":                "规格 CPU 范围",
	"flavor_family":                  "规格族",
	"flavor_family_list":             "规格族列表",
	"flavor_family_scope":            "规格族范围",
	"flavor_name_scope":              "规格名称范围",
	"flavor_ram":                     "规格内存",
	"flavor_ramscope":                "规格内存范围",
	"flavor_series":                  "规格系列",
	"flavor_set_type":                "规格集合类型",
	"gray_type":                      "灰度类型",
	"gpu_manufacturer":               "GPU 厂商",
	"health_mode":                    "健康检查方式",
	"health_period":                  "健康检查周期",
	"health_status":                  "健康状态",
	"inner_ip":                       "内网 IP",
	"ip_address":                     "IP 地址",
	"is_version":                     "是否为版本",
	"ksvc_name":                      "服务名称",
	"layout_type":                    "布局类型",
	"master_node_quantity":           "管控节点数量",
	"max_async_event_age_in_seconds": "异步事件最大存活时间",
	"max_async_retry_attempts":       "异步调用重试次数",
	"max_count":                      "最大数量",
	"mem_size":                       "内存大小",
	"message":                        "消息",
	"method":                         "请求方法",
	"min_count":                      "最小数量",
	"move_out_strategy":              "实例移出策略",
	"network_interface_name":         "网卡名称",
	"name_en":                        "英文名称",
	"name_zh":                        "中文名称",
	"numa_node_amount":               "单个 CPU NUMA 节点数量",
	"nvme_volume_interface":          "NVMe 云硬盘接口",
	"on_demand":                      "是否按需付费",
	"openapi_available":              "OpenAPI 可用",
	"operate_unit":                   "操作单位",
	"oss_mount":                      "ZOS 挂载配置",
	"owner":                          "所有者",
	"period":                         "监控周期",
	"plugin_status":                  "插件状态",
	"pps":                            "网络收发包能力",
	"protect_status":                 "保护状态",
	"public_ip":                      "公网 IP",
	"public_key":                     "公钥",
	"recovery_mode":                  "实例回收模式",
	"results":                        "结果",
	"return_obj":                     "返回结果",
	"reserved_concurrency":           "预留并发数",
	"retention_type":                 "保留类型",
	"revision":                       "版本修订号",
	"rpo":                            "RPO",
	"rpoload_cnt":                    "RPO 过高数量",
	"rule_execution_result":          "策略执行结果",
	"security_group_id_list":         "安全组 ID 列表",
	"standard_value":                 "标准值",
	"start_time":                     "开始时间",
	"statistics":                     "聚合方式",
	"status_code":                    "状态码",
	"system_volume_interface":        "系统盘接口",
	"system_volume_type":             "系统盘类型",
	"trigger_config":                 "触发器配置",
	"trigger_type":                   "触发器类型",
	"trust_status":                   "可信状态",
	"type_code":                      "容灾类型",
	"url_internet":                   "外网 URL",
	"url_intranet":                   "内网 URL",
	"update_time":                    "更新时间",
	"use_lb":                         "是否使用负载均衡",
	"visibility":                     "可见性",
	"v_list":                         "伸缩实例监控列表",
	"version":                        "版本",
	"version_id":                     "版本 ID",
	"vpc_ids":                        "VPC ID 列表",
	"zabbix_name":                    "监控设备 ID",
	"accept_account_type":            "对端账号类型",
	"auto_delete":                    "是否自动删除",
	"band_width":                     "带宽",
	"base_band_width":                "基准带宽",
	"batch_order_placement_results":  "订单结果",
	"bill_mode":                      "订购类型",
	"bind_obj_type":                  "绑定对象类型",
	"charge_type":                    "计费方式",
	"charge_ver":                     "防火墙规格版本",
	"complete_org_name":              "完整部门名称",
	"concurrent_mode":                "并发模式",
	"concurrent_rate":                "最大并发比例",
	"cpu_remaining":                  "剩余 CPU 核数",
	"cycle_day_cnt":                  "快照周期天数",
	"cycle_type":                     "周期类型",
	"days_of_week":                   "每周快照日",
	"deduction_end_time":             "核时结束时间",
	"deduction_start_time":           "核时开始时间",
	"desktop_admin_priv":             "账号权限",
	"desktop_oid":                    "云电脑 ID",
	"desktop_pool":                   "桌面池",
	"destination_port":               "目的端口",
	"device_ip_address":              "设备 IP 地址",
	"device_mac_address":             "设备 MAC 地址",
	"device_private_ip_address":      "设备私网 IP 地址",
	"device_sn_code":                 "设备序列号",
	"disk_remaining":                 "剩余磁盘空间",
	"encryption":                     "是否加密",
	"end_connect_time":               "结束连接时间",
	"error_message":                  "错误信息",
	"expire_time":                    "到期时间",
	"final_price":                    "最终价格",
	"flavor_subtype":                 "规格子类型",
	"for_sys_disk":                   "是否为系统盘",
	"lock_status":                    "锁定状态",
	"manage_status":                  "管理状态",
	"max_band_width":                 "最大带宽",
	"max_concurrent_desktop_count":   "最大并发云电脑数",
	"memory_remaining":               "剩余内存",
	"mirror_type":                    "镜像类型",
	"multi_card":                     "GPU 多卡数量",
	"new_order_id":                   "新订单 ID",
	"new_order_no":                   "新订单号",
	"open_sms_switch":                "是否开启短信告警",
	"operation":                      "操作",
	"operation_id":                   "操作 ID",
	"operation_ids":                  "操作 ID 列表",
	"operations":                     "操作列表",
	"order_item_prices":              "价格子项",
	"order_sum_item_prices":          "汇总价格子项",
	"org_name":                       "部门名称",
	"org_oid":                        "部门 ID",
	"os_bits":                        "操作系统位数",
	"par_template_oid":               "父卡规格模板 ID",
	"platform":                       "操作系统平台",
	"port_list":                      "网卡列表",
	"port_sg_list":                   "网卡安全组列表",
	"processor_type":                 "处理器类型",
	"properties":                     "附加属性",
	"protocol":                       "协议",
	"pub_user_oid":                   "分配用户 ID",
	"retention_cnt":                  "保留数量",
	"retention_day_cnt":              "保留天数",
	"retention_month_cnt":            "保留月数",
	"retention_rule":                 "保留规则",
	"share_flag":                     "是否共享",
	"snapshot_time_points":           "快照时间点",
	"source":                         "来源",
	"source_port":                    "源端口",
	"spec":                           "规格",
	"start_connect_time":             "开始连接时间",
	"strategy":                       "策略",
	"sub_order_prices":               "子订单价格",
	"submitted":                      "是否提交成功",
	"subnet_ip_address":              "子网 IP 地址",
	"sys_disk_size":                  "系统盘大小",
	"total_price":                    "总价",
	"usage_hours":                    "使用时长",
	"user_account":                   "用户账号",
	"user_name":                      "用户名称",
	"video_url":                      "视频 URL",
}
