/*
 * Copyright (c) 2026 IsArvin.
 * This file is part of ctyun-cli. Please refer to the LICENCE file for licence information.
 */

package cli

import (
	"bytes"
	"os"
	"os/exec"
	"path/filepath"
	"strconv"
	"strings"
	"testing"
)

// TestCompletionShellPreservesCursorArguments executes generated shell glue
// and checks that the resolver receives separate words only through the cursor.
func TestCompletionShellPreservesCursorArguments(t *testing.T) {
	for _, shell := range []string{"bash", "zsh"} {
		path, err := exec.LookPath(shell)
		if err != nil {
			t.Logf("%s unavailable: shell execution checks skipped", shell)
			continue
		}
		for _, test := range []struct {
			name, words, want string
			cursor            int
		}{
			{"empty final word", "ctyun plugin list ''", "__complete\nplugin\nlist\n\n", 3},
			{"earlier word", "ctyun plugin li --available", "__complete\nplugin\nli\n", 2},
			{"quoted word", "ctyun --profile 'two words' plugin li", "__complete\n--profile\ntwo words\nplugin\nli\n", 4},
		} {
			t.Run(shell+"/"+test.name, func(t *testing.T) {
				var generated bytes.Buffer
				if err := runCompletion(&generated, []string{shell}); err != nil {
					t.Fatal(err)
				}
				capture := filepath.Join(t.TempDir(), "arguments")
				setup := "ctyun() { printf '%s\\n' \"$@\" > \"$CTYUN_COMPLETION_CAPTURE\"; }; compadd() { :; };\n"
				var script string
				if shell == "bash" {
					script = setup + generated.String() + "\nCOMP_WORDS=(" + test.words + "); COMP_CWORD=" + strconv.Itoa(test.cursor) + "; _ctyun_completion\n"
				} else {
					script = setup + "words=(" + test.words + "); CURRENT=" + strconv.Itoa(test.cursor+1) + ";\n" + generated.String()
				}
				command := exec.Command(path, "-c", script)
				command.Env = append(os.Environ(), "CTYUN_COMPLETION_CAPTURE="+capture)
				if output, err := command.CombinedOutput(); err != nil {
					t.Fatalf("execute completion: %v\n%s", err, output)
				}
				got, err := os.ReadFile(capture)
				if err != nil {
					t.Fatal(err)
				}
				if string(got) != test.want {
					t.Fatalf("resolver arguments = %q, want %q", got, test.want)
				}
			})
		}
	}
}

// TestPowerShellCompletionBoundsASTArguments guards cursor and quoted-value
// handling where PowerShell is unavailable to execute the generated completer.
func TestPowerShellCompletionBoundsASTArguments(t *testing.T) {
	var generated bytes.Buffer
	if err := runCompletion(&generated, []string{"powershell"}); err != nil {
		t.Fatal(err)
	}
	for _, required := range []string{
		"$element.Extent.EndOffset -ge $cursorPosition",
		"$element.Value",
		"$arguments += $wordToComplete",
	} {
		if !strings.Contains(generated.String(), required) {
			t.Errorf("PowerShell completer is missing cursor/argument guard %q", required)
		}
	}
}
